import React, { useState } from 'react';
import { useParams } from "react-router-dom";
import { connect } from 'react-redux';
import { get, set } from 'automate-redux';
import client from '../../../client';
import Sidenav from '../../../components/sidenav/Sidenav';
import Topbar from '../../../components/topbar/Topbar';
import { InfoCircleOutlined } from '@ant-design/icons';
import { Checkbox, Input, Tooltip, Button, Typography } from 'antd';
import '../explorer.css';
import GraphiQL from 'graphiql';
import 'graphiql/graphiql.css';
import ExplorerTabs from "../../../components/explorer/explorer-tabs/ExplorerTabs"
import GenerateTokenForm from "../../../components/explorer/generateToken/GenerateTokenForm"
import { getAPIToken } from '../../../operations/projects';
import { projectModules } from '../../../constants';
import { canGenerateToken, getGraphQLEndpoints } from '../../../utils';

const Graphql = props => {

  const { projectID } = useParams();

  const [generateTokenModal, setGenerateTokenModal] = useState(false)

  const getToken = () => {
    return props.useInternalToken ? props.internalToken : props.userToken
  }

  const graphQLFetcher = (graphQLParams, projectId) => {
    return client.execGraphQLQuery(
      projectId,
      graphQLParams.query,
      graphQLParams.variables,
      getToken()
    );
  }

  const { httpUrl } = getGraphQLEndpoints(projectID)

  return (
    <div className='explorer'>
      <Topbar showProjectSelector />
      <Sidenav selectedItem={projectModules.EXPLORER} />
      <div className='page-content page-content--no-padding'>
        <ExplorerTabs activeKey="graphql" projectID={projectID} />
        <div style={{ padding: "32px 32px 0" }}>
          <div className="row">
            <h3>GraphQL endpoint</h3>
            <div style={{
              lineHeight: "38px",
              border: "1px solid #f0f0f0"
            }}>
              <div style={{
                display: "inline-block",
                padding: "0 16px",
                borderRight: "1px solid #f0f0f0",
                backgroundColor: "#fafafa",
                color: "#fd9540",
                fontWeight: "bold"
              }}>
                POST
              </div>
              <div style={{
                display: "inline-block",
                padding: "0 16px"
              }}>
                <Typography.Text copyable={true}>
                  {httpUrl}
                </Typography.Text>
              </div>
            </div>
          </div>
          <div className='row'>
            <Checkbox
              checked={props.useInternalToken}
              onChange={e =>
                props.setUseInternalToken(e.target.checked)
              }
            >
              Bypass security rules
                        </Checkbox>
            <Tooltip
              placement='bottomLeft'
              title='Use an internal token generated by Space Cloud to bypass all security rules for this request '
            >
              <InfoCircleOutlined style={{ color: 'rgba(0,0,0,.45)' }} />
            </Tooltip>
          </div>
          {!props.useInternalToken && (
            <div className='row' style={{ display: "flex" }}>
              <Input.Password
                placeholder='JWT Token'
                value={props.userToken}
                onChange={e => props.setUserToken(e.target.value)}
              />
              <Tooltip title={props.generateTokenAllowed ? "" : "You are not allowed to perform this action. This action requires modify permissions on project config"}>
                <Button disabled={!props.generateTokenAllowed} onClick={() => setGenerateTokenModal(true)}>Generate Token</Button>
              </Tooltip>
            </div>
          )
          }
          <div className='graphql' style={{ marginTop: 10 }}>
            <GraphiQL
              query={props.query ? props.query : undefined}
              variables={props.variables ? props.variables : undefined}
              onEditQuery={props.setGraphQLQuery}
              onEditVariables={props.setGraphQLVariables}
              fetcher={graphQLParams =>
                graphQLFetcher(graphQLParams, props.projectId)
              }
              schema={null}
            />
          </div>
        </div>
        {generateTokenModal && <GenerateTokenForm
          handleCancel={() => setGenerateTokenModal(false)}
          handleSubmit={props.setUserToken}
          initialToken={getToken()}
          projectID={projectID}
        />}
      </div>
    </div >
  );

};

const mapStateToProps = (state, ownProps) => {
  const projectId = ownProps.match.params.projectID
  return {
    projectId: projectId,
    query: state.uiState.graphiql.query,
    variables: state.uiState.graphiql.variables,
    useInternalToken: get(
      state,
      'uiState.explorer.useInternalToken',
      true
    ),
    userToken: get(state, 'uiState.explorer.userToken'),
    internalToken: getAPIToken(state),
    generateTokenAllowed: canGenerateToken(state, projectId)
  };
};

const mapDispatchToProps = dispatch => {
  return {
    setUseInternalToken: (useInternalToken) => {
      dispatch(set('uiState.explorer.useInternalToken', useInternalToken))
    },
    setUserToken: (userToken) => {
      dispatch(set('uiState.explorer.userToken', userToken))
    },
    setGraphQLQuery: (query) => {
      dispatch(set('uiState.graphiql.query', query))
    },
    setGraphQLVariables: (variables) => {
      dispatch(set('uiState.graphiql.variables', variables))
    }
  };
};

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Graphql);