// config
import { removeDbConfig, loadDbConfig, loadDBConnState, addDatabase, enableDb, disableDb, changeDbName, getDbConfigs, getDbConfig, getDbName, getDbType, getDbConnState, getDbConnectionString } from './config';
// prepared-query
import { loadDbPreparedQueries, savePreparedQuerySecurityRule, savePreparedQueryConfig, deletePreparedQuery, getDbPreparedQueries, getDbPreparedQuery, getDbDefaultPreparedQuerySecurityRule, getDbDefaultCollectionSecurityRule, getPreparedQuerySecurityRule, isPreparedQueriesSupported, isPreparedQueriesSupportedForDbType, setPreparedQueryRule } from './preparedQuery';
// collections
import { saveColRealtimeEnabled, untrackCollection, deleteCollection, getCollections, loadDbSchemas, inspectColSchema, saveColSchema, reloadDbSchema, modifyDbSchema, getCollectionSchema, getDbSchema, getDbSchemas, loadDbRules, saveColSecurityRules, getDbRules, getCollectionRules, getCollectionSecurityRule, getTrackedCollectionsInfo, getTrackedCollections, getDbGraphQLRootFields, getUntrackedCollections, setColSecurityRule } from './collections';

export default {
  removeDbConfig,
  loadDbConfig,
  loadDbSchemas,
  loadDbRules,
  loadDbPreparedQueries,
  loadDBConnState,
  inspectColSchema,
  saveColSchema,
  saveColRealtimeEnabled,
  untrackCollection,
  deleteCollection,
  savePreparedQueryConfig,
  deletePreparedQuery,
  reloadDbSchema,
  modifyDbSchema,
  addDatabase,
  enableDb,
  disableDb,
  changeDbName,
  getDbConfigs,
  getDbConfig,
  getDbName,
  getDbType,
  getDbConnState,
  getCollectionSchema,
  getDbSchema,
  getDbSchemas,
  getDbRules,
  getDbPreparedQueries,
  getDbPreparedQuery,
  getDbDefaultPreparedQuerySecurityRule,
  getDbDefaultCollectionSecurityRule,
  getCollections,
  getDbConnectionString,
  getCollectionRules,
  getCollectionSecurityRule,
  getPreparedQuerySecurityRule,
  getTrackedCollectionsInfo,
  getTrackedCollections,
  getDbGraphQLRootFields,
  getUntrackedCollections,
  setPreparedQueryRule,
  setColSecurityRule,
  isPreparedQueriesSupported,
  isPreparedQueriesSupportedForDbType,
  saveColSecurityRules,
  savePreparedQuerySecurityRule
}